export default const list = [
  {
    "title": "运单记录",
    "id": 117,
    "parent_id": 81,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "users@order",
    "hidden": 1
  },
  {
    "title": "钱包流水",
    "id": 116,
    "parent_id": 81,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "users@flow",
    "hidden": 1
  },
  {
    "title": "读取",
    "id": 101,
    "parent_id": 81,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "users@read",
    "hidden": 1
  },
  {
    "title": "导入",
    "id": 100,
    "parent_id": 81,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "users@import",
    "hidden": 1
  },
  {
    "title": "审核账号",
    "id": 211,
    "parent_id": 81,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "users@examine",
    "hidden": 1
  },
  {
    "title": "删除",
    "id": 99,
    "parent_id": 81,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "users@delete",
    "hidden": 1
  },
  {
    "title": "删除",
    "id": 223,
    "parent_id": 85,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "powerPlat@delete",
    "hidden": 1
  },
  {
    "title": "更新",
    "id": 98,
    "parent_id": 81,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "users@update",
    "hidden": 1
  },
  {
    "title": "编辑",
    "id": 222,
    "parent_id": 85,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "powerPlat@update",
    "hidden": 1
  },
  {
    "title": "设置合同",
    "id": 210,
    "parent_id": 81,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "users@hzSetContract",
    "hidden": 1
  },
  {
    "title": "创建",
    "id": 97,
    "parent_id": 81,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "users@save",
    "hidden": 1
  },
  {
    "title": "导出",
    "id": 233,
    "parent_id": 81,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "users@exportHz",
    "hidden": 1
  },
  {
    "title": "新增",
    "id": 221,
    "parent_id": 85,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "powerPlat@save",
    "hidden": 1
  },
  {
    "title": "列表",
    "id": 94,
    "parent_id": 81,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "users@index",
    "hidden": 1
  },
  {
    "title": "意见反馈",
    "id": 292,
    "parent_id": 75,
    "route": "/feedfback",
    "icon": "el-icon-s-comment",
    "component": "cmsFeedfback",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "feedfback",
    "hidden": 1
  },
  {
    "title": "消息管理",
    "id": 146,
    "parent_id": 75,
    "route": "/cmsMessage",
    "icon": "el-icon-s-order",
    "component": "cmsMessage",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "announce",
    "hidden": 1
  },
  {
    "title": "权限管理",
    "id": 1,
    "parent_id": 0,
    "route": "/permissions",
    "icon": "el-icon-cpu",
    "component": "layout",
    "redirect": "/permissions/users",
    "module": "permissions",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "permission",
    "hidden": 1
  },
  {
    "title": "消息模板",
    "id": 173,
    "parent_id": 75,
    "route": "/cmsAnnounceTemplate",
    "icon": "el-icon-message-solid",
    "component": "cmsMessageTemplate",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "announceTemplate",
    "hidden": 1
  },
  {
    "title": "订单管理",
    "id": 311,
    "parent_id": 0,
    "route": "/cmsOrder",
    "icon": "el-icon-s-order",
    "component": "layout",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "cms",
    "hidden": 1
  },
  {
    "title": "数据字典",
    "id": 306,
    "parent_id": 38,
    "route": "/dictionary",
    "icon": "el-icon-menu",
    "component": "dictionary",
    "redirect": "",
    "module": "system",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "dictionary",
    "hidden": 1
  },
  {
    "title": "重量区间列表",
    "id": 302,
    "parent_id": 73,
    "route": "/cmsPriceWeightSon/:id",
    "icon": "",
    "component": "cmsPriceWeightSon",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "priceConfigData",
    "hidden": 2
  },
  {
    "title": "重量管理",
    "id": 296,
    "parent_id": 73,
    "route": "cmsPriceWeight",
    "icon": "el-icon-s-operation",
    "component": "cmsPriceWeight",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "priceConfig",
    "hidden": 1
  },
  {
    "title": "里程区间列表",
    "id": 301,
    "parent_id": 73,
    "route": "/cmsPriceMileageSon/:id?",
    "icon": "el-icon-plus",
    "component": "cmsPriceMileageSon",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "priceConfigData",
    "hidden": 2
  },
  {
    "title": "里程管理",
    "id": 295,
    "parent_id": 73,
    "route": "/cmsPriceMileage",
    "icon": "el-icon-s-operation",
    "component": "cmsPriceMileage",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "priceConfig",
    "hidden": 1
  },
  {
    "title": "确认收货",
    "id": 229,
    "parent_id": 83,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "order@handleSmHsOrder",
    "hidden": 1
  },
  {
    "title": "货主管理",
    "id": 81,
    "parent_id": 76,
    "route": "/cmsHuozhu",
    "icon": "el-icon-user-solid",
    "component": "cmsHuozhu",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "users",
    "hidden": 1
  },
  {
    "title": "取消订单",
    "id": 228,
    "parent_id": 83,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "order@cancelOrder",
    "hidden": 1
  },
  {
    "title": "系统订单平台收款",
    "id": 227,
    "parent_id": 83,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "order@xtGfPay",
    "hidden": 1
  },
  {
    "title": "审核",
    "id": 217,
    "parent_id": 88,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "driver@driverCheck",
    "hidden": 1
  },
  {
    "title": "派单",
    "id": 226,
    "parent_id": 83,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "order@dispatchDriver",
    "hidden": 1
  },
  {
    "title": "重置密码",
    "id": 216,
    "parent_id": 88,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "driver@updatePwd",
    "hidden": 1
  },
  {
    "title": "读取",
    "id": 161,
    "parent_id": 143,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "reimbursement@read",
    "hidden": 1
  },
  {
    "title": "导入",
    "id": 215,
    "parent_id": 88,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "driver@import",
    "hidden": 1
  },
  {
    "title": "设置货主账号",
    "id": 209,
    "parent_id": 74,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "site@siteSetHz",
    "hidden": 1
  },
  {
    "title": "导入",
    "id": 208,
    "parent_id": 77,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "carType@import",
    "hidden": 1
  },
  {
    "title": "导出",
    "id": 200,
    "parent_id": 162,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "staffCommission@export",
    "hidden": 1
  },
  {
    "title": "更新",
    "id": 171,
    "parent_id": 80,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "announce@update",
    "hidden": 1
  },
  {
    "title": "审核",
    "id": 160,
    "parent_id": 143,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "reimbursement@examine",
    "hidden": 1
  },
  {
    "title": "品类管理",
    "id": 144,
    "parent_id": 73,
    "route": "/cmsClasses",
    "icon": "el-icon-help",
    "component": "cmsClassesNew",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "classes",
    "hidden": 1
  },
  {
    "title": "报销管理",
    "id": 143,
    "parent_id": 140,
    "route": "/cmsReimbursement",
    "icon": "el-icon-s-finance",
    "component": "cmsReimbursement",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "reimbursement",
    "hidden": 1
  },
  {
    "title": "读取",
    "id": 132,
    "parent_id": 79,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "gift@read",
    "hidden": 1
  },
  {
    "title": "读取",
    "id": 127,
    "parent_id": 78,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "agreement@read",
    "hidden": 1
  },
  {
    "title": "业务管理",
    "id": 76,
    "parent_id": 0,
    "route": "/cmsBusiness",
    "icon": "el-icon-s-marketing",
    "component": "layout",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "cms",
    "hidden": 1
  },
  {
    "title": "删除",
    "id": 231,
    "parent_id": 82,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "hzAddress@delete",
    "hidden": 1
  },
  {
    "title": "删除",
    "id": 214,
    "parent_id": 88,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "driver@delete",
    "hidden": 1
  },
  {
    "title": "批量发放",
    "id": 199,
    "parent_id": 162,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "staffCommission@updateBatch",
    "hidden": 1
  },
  {
    "title": "上传凭证",
    "id": 189,
    "parent_id": 184,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "payState@payStateUploadInvoice",
    "hidden": 1
  },
  {
    "title": "货主解约",
    "id": 182,
    "parent_id": 76,
    "route": "/cmsHuozhuSecure",
    "icon": "el-icon-user-solid",
    "component": "cmsHuozhuSecure",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "HzContract",
    "hidden": 1
  },
  {
    "title": "列表",
    "id": 177,
    "parent_id": 173,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "announceTemplate@index",
    "hidden": 1
  },
  {
    "title": "取消",
    "id": 159,
    "parent_id": 143,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "reimbursement@cancel",
    "hidden": 1
  },
  {
    "title": "列表",
    "id": 156,
    "parent_id": 152,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "reimbursementType@index",
    "hidden": 1
  },
  {
    "title": "列表",
    "id": 151,
    "parent_id": 147,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "carFixLog@index",
    "hidden": 1
  },
  {
    "title": "删除",
    "id": 135,
    "parent_id": 80,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "announce@delete",
    "hidden": 1
  },
  {
    "title": "删除",
    "id": 131,
    "parent_id": 79,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "gift@delete",
    "hidden": 1
  },
  {
    "title": "更新",
    "id": 126,
    "parent_id": 78,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "agreement@update",
    "hidden": 1
  },
  {
    "title": "更新",
    "id": 122,
    "parent_id": 83,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "order@update",
    "hidden": 1
  },
  {
    "title": "更新",
    "id": 115,
    "parent_id": 72,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "priceStandard@update",
    "hidden": 1
  },
  {
    "title": "删除",
    "id": 109,
    "parent_id": 77,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "carType@delete",
    "hidden": 1
  },
  {
    "title": "删除",
    "id": 105,
    "parent_id": 74,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "site@delete",
    "hidden": 1
  },
  {
    "title": "应用管理",
    "id": 75,
    "parent_id": 0,
    "route": "/cmsApply",
    "icon": "el-icon-menu",
    "component": "layout",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "cms",
    "hidden": 1
  },
  {
    "title": "新增",
    "id": 230,
    "parent_id": 82,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "hzAddress@save",
    "hidden": 1
  },
  {
    "title": "删除",
    "id": 220,
    "parent_id": 87,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "car@delete",
    "hidden": 1
  },
  {
    "title": "编辑",
    "id": 213,
    "parent_id": 88,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "driver@update",
    "hidden": 1
  },
  {
    "title": "删除",
    "id": 206,
    "parent_id": 144,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "classes@delete",
    "hidden": 1
  },
  {
    "title": "上传凭证",
    "id": 203,
    "parent_id": 183,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "receiveState@receStateUploadInvoice",
    "hidden": 1
  },
  {
    "title": "删除",
    "id": 195,
    "parent_id": 170,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "powerClass@delete",
    "hidden": 1
  },
  {
    "title": "删除",
    "id": 192,
    "parent_id": 145,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "limitPrice@delete",
    "hidden": 1
  },
  {
    "title": "删除",
    "id": 188,
    "parent_id": 184,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "payState@delete",
    "hidden": 1
  },
  {
    "title": "删除",
    "id": 176,
    "parent_id": 173,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "announceTemplate@delete",
    "hidden": 1
  },
  {
    "title": "列表",
    "id": 166,
    "parent_id": 162,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "staffCommission@index",
    "hidden": 1
  },
  {
    "title": "列表",
    "id": 158,
    "parent_id": 143,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "reimbursement@index",
    "hidden": 1
  },
  {
    "title": "删除",
    "id": 155,
    "parent_id": 152,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "reimbursementType@delete",
    "hidden": 1
  },
  {
    "title": "删除",
    "id": 150,
    "parent_id": 147,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "carFixLog@delete",
    "hidden": 1
  },
  {
    "title": "创建",
    "id": 134,
    "parent_id": 80,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "announce@save",
    "hidden": 1
  },
  {
    "title": "更新",
    "id": 130,
    "parent_id": 79,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "gift@update",
    "hidden": 1
  },
  {
    "title": "删除",
    "id": 125,
    "parent_id": 78,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "agreement@delete",
    "hidden": 1
  },
  {
    "title": "读取",
    "id": 121,
    "parent_id": 83,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "order@index",
    "hidden": 1
  },
  {
    "title": "创建",
    "id": 114,
    "parent_id": 72,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "priceStandard@save",
    "hidden": 1
  },
  {
    "title": "更新",
    "id": 108,
    "parent_id": 77,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "carType@update",
    "hidden": 1
  },
  {
    "title": "更新",
    "id": 104,
    "parent_id": 74,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "site@update",
    "hidden": 1
  },
  {
    "title": "编辑",
    "id": 219,
    "parent_id": 87,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "car@update",
    "hidden": 1
  },
  {
    "title": "编辑",
    "id": 205,
    "parent_id": 144,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "classes@update",
    "hidden": 1
  },
  {
    "title": "企业账单上传凭证",
    "id": 202,
    "parent_id": 183,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "receiveState@comStateUploadInvoice",
    "hidden": 1
  },
  {
    "title": "导出",
    "id": 198,
    "parent_id": 141,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "withdraApply@export",
    "hidden": 1
  },
  {
    "title": "更新",
    "id": 194,
    "parent_id": 170,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "powerClass@update",
    "hidden": 1
  },
  {
    "title": "更新",
    "id": 191,
    "parent_id": 145,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "limitPrice@update",
    "hidden": 1
  },
  {
    "title": "更新",
    "id": 187,
    "parent_id": 184,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "payState@update",
    "hidden": 1
  },
  {
    "title": "更新",
    "id": 175,
    "parent_id": 173,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "announceTemplate@update",
    "hidden": 1
  },
  {
    "title": "创建",
    "id": 172,
    "parent_id": 146,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "announce@sendHzAnnou",
    "hidden": 1
  },
  {
    "title": "创建",
    "id": 165,
    "parent_id": 162,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "staffCommission@save",
    "hidden": 1
  },
  {
    "title": "创建",
    "id": 157,
    "parent_id": 143,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "reimbursement@save",
    "hidden": 1
  },
  {
    "title": "更新",
    "id": 154,
    "parent_id": 152,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "reimbursementType@update",
    "hidden": 1
  },
  {
    "title": "更新",
    "id": 149,
    "parent_id": 147,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "carFixLog@update",
    "hidden": 1
  },
  {
    "title": "列表",
    "id": 133,
    "parent_id": 80,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "announce@index",
    "hidden": 1
  },
  {
    "title": "创建",
    "id": 129,
    "parent_id": 79,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "gift@save",
    "hidden": 1
  },
  {
    "title": "创建",
    "id": 124,
    "parent_id": 78,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "agreement@save",
    "hidden": 1
  },
  {
    "title": "删除",
    "id": 120,
    "parent_id": 83,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "order@delete",
    "hidden": 1
  },
  {
    "title": "删除",
    "id": 113,
    "parent_id": 72,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "priceStandard@delete",
    "hidden": 1
  },
  {
    "title": "创建",
    "id": 107,
    "parent_id": 77,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "carType@save",
    "hidden": 1
  },
  {
    "title": "创建",
    "id": 103,
    "parent_id": 74,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "site@save",
    "hidden": 1
  },
  {
    "title": "列表",
    "id": 96,
    "parent_id": 82,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "hzAddress@index",
    "hidden": 1
  },
  {
    "title": "审核",
    "id": 241,
    "parent_id": 182,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "HzContract@hzJyCheck",
    "hidden": 1
  },
  {
    "title": "公账确认到账",
    "id": 224,
    "parent_id": 84,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "recharge@checkPay",
    "hidden": 1
  },
  {
    "title": "新增",
    "id": 218,
    "parent_id": 87,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "car@save",
    "hidden": 1
  },
  {
    "title": "新增",
    "id": 212,
    "parent_id": 88,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "driver@save",
    "hidden": 1
  },
  {
    "title": "启用/禁用",
    "id": 207,
    "parent_id": 168,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "area@update",
    "hidden": 1
  },
  {
    "title": "新增",
    "id": 204,
    "parent_id": 144,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "classes@save",
    "hidden": 1
  },
  {
    "title": "生成企业应收对账单",
    "id": 201,
    "parent_id": 183,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "receiveState@createCompanyState",
    "hidden": 1
  },
  {
    "title": "拒绝",
    "id": 197,
    "parent_id": 141,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "withdraApply@paymentRefuse",
    "hidden": 1
  },
  {
    "title": "新增",
    "id": 193,
    "parent_id": 170,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "powerClass@save",
    "hidden": 1
  },
  {
    "title": "创建",
    "id": 190,
    "parent_id": 145,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "limitPrice@save",
    "hidden": 1
  },
  {
    "title": "创建",
    "id": 186,
    "parent_id": 184,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "payState@save",
    "hidden": 1
  },
  {
    "title": "创建",
    "id": 174,
    "parent_id": 173,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "announceTemplate@save",
    "hidden": 1
  },
  {
    "title": "删除",
    "id": 164,
    "parent_id": 162,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "staffCommission@delete",
    "hidden": 1
  },
  {
    "title": "创建",
    "id": 153,
    "parent_id": 152,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "reimbursementType@save",
    "hidden": 1
  },
  {
    "title": "创建",
    "id": 148,
    "parent_id": 147,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "carFixLog@save",
    "hidden": 1
  },
  {
    "title": "列表",
    "id": 128,
    "parent_id": 79,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "gift@index",
    "hidden": 1
  },
  {
    "title": "列表",
    "id": 123,
    "parent_id": 78,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "agreement@index",
    "hidden": 1
  },
  {
    "title": "列表",
    "id": 118,
    "parent_id": 83,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "order@index",
    "hidden": 1
  },
  {
    "title": "列表",
    "id": 110,
    "parent_id": 72,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "priceStandard@index",
    "hidden": 1
  },
  {
    "title": "列表",
    "id": 106,
    "parent_id": 77,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "carType@index",
    "hidden": 1
  },
  {
    "title": "列表",
    "id": 102,
    "parent_id": 74,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "site@index",
    "hidden": 1
  },
  {
    "title": "更新",
    "id": 95,
    "parent_id": 82,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "hzAddress@update",
    "hidden": 1
  },
  {
    "title": "短信管理",
    "id": 310,
    "parent_id": 76,
    "route": "/messagecode",
    "icon": "el-icon-s-promotion",
    "component": "cmsMessageCode",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "cms",
    "hidden": 1
  },
  {
    "title": "录入打款凭证",
    "id": 196,
    "parent_id": 141,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "withdraApply@paymentUpdate",
    "hidden": 1
  },
  {
    "title": "电厂品类",
    "id": 170,
    "parent_id": 169,
    "route": "/cmsPowerClass",
    "icon": "el-icon-video-camera",
    "component": "cmsPowerClass",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "powerClass",
    "hidden": 1
  },
  {
    "title": "更新",
    "id": 163,
    "parent_id": 162,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "staffCommission@update",
    "hidden": 1
  },
  {
    "title": "品类限时特价",
    "id": 145,
    "parent_id": 73,
    "route": "/cmsLimitPrice",
    "icon": "el-icon-coffee-cup",
    "component": "cmsLimitPriceNew",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "limitPrice",
    "hidden": 1
  },
  {
    "title": "提现管理",
    "id": 141,
    "parent_id": 140,
    "route": "/cmsWithdraApply",
    "icon": "el-icon-s-promotion",
    "component": "cmsWithdraApplyNew",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "withdraApply",
    "hidden": 1
  },
  {
    "title": "平台管理",
    "id": 73,
    "parent_id": 0,
    "route": "/cmsPlat",
    "icon": "el-icon-box",
    "component": "layout",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "cms",
    "hidden": 1
  },
  {
    "title": "附件管理",
    "id": 44,
    "parent_id": 38,
    "route": "/system/attactments",
    "icon": "el-icon-folder-opened",
    "component": "attachment",
    "redirect": "",
    "module": "system",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "attactments",
    "hidden": 1
  },
  {
    "title": "列表",
    "id": 41,
    "parent_id": 39,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "system",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "dataDictionary@tables",
    "hidden": 1
  },
  {
    "title": "用户管理",
    "id": 2,
    "parent_id": 1,
    "route": "/permissions/users",
    "icon": "el-icon-user",
    "component": "users",
    "redirect": "",
    "module": "permissions",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "user",
    "hidden": 1
  },
  {
    "title": "系统订单",
    "id": 312,
    "parent_id": 311,
    "route": "/systemOrderList",
    "icon": "el-icon-s-tools",
    "component": "cmsSystemOrderList",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "order",
    "hidden": 1
  },
  {
    "title": "车辆维修记录",
    "id": 147,
    "parent_id": 76,
    "route": "/cmsCarFix",
    "icon": "el-icon-warning",
    "component": "cmsCarFix",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "carFixLog",
    "hidden": 1
  },
  {
    "title": "配置管理",
    "id": 49,
    "parent_id": 38,
    "route": "/system/config",
    "icon": "el-icon-setting",
    "component": "config",
    "redirect": "",
    "module": "system",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "config",
    "hidden": 1
  },
  {
    "title": "角色管理",
    "id": 11,
    "parent_id": 1,
    "route": "/permissions/roles",
    "icon": "el-icon-s-custom",
    "component": "roles",
    "redirect": "",
    "module": "permissions",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "role",
    "hidden": 1
  },
  {
    "title": "待接单订单",
    "id": 313,
    "parent_id": 311,
    "route": "/waitingOrderList",
    "icon": "el-icon-s-order",
    "component": "cmsWaitingOrderList",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "order",
    "hidden": 1
  },
  {
    "title": "司机管理",
    "id": 88,
    "parent_id": 76,
    "route": "/cmsDriver",
    "icon": "el-icon-s-custom",
    "component": "cmsDriver",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "driver",
    "hidden": 1
  },
  {
    "title": "表结构",
    "id": 39,
    "parent_id": 38,
    "route": "/system/database",
    "icon": "el-icon-copy-document",
    "component": "database",
    "redirect": "",
    "module": "system",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "dataDictionary",
    "hidden": 1
  },
  {
    "title": "菜单管理",
    "id": 19,
    "parent_id": 1,
    "route": "/permissions/rules",
    "icon": "el-icon-collection-tag",
    "component": "rules",
    "redirect": "",
    "module": "permissions",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "permission",
    "hidden": 1
  },
  {
    "title": "内部提成",
    "id": 162,
    "parent_id": 140,
    "route": "/cmsStaffCommission",
    "icon": "el-icon-money",
    "component": "cmsStaffCommission",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "staffCommission",
    "hidden": 1
  },
  {
    "title": "车辆管理",
    "id": 87,
    "parent_id": 76,
    "route": "/cmsCar",
    "icon": "el-icon-odometer",
    "component": "cmsCar",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "car",
    "hidden": 1
  },
  {
    "title": "部门管理",
    "id": 27,
    "parent_id": 1,
    "route": "/permissions/departments",
    "icon": "el-icon-monitor",
    "component": "departments",
    "redirect": "",
    "module": "permissions",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "departments",
    "hidden": 1
  },
  {
    "title": "待审核订单",
    "id": 314,
    "parent_id": 311,
    "route": "/reviewOrderList",
    "icon": "el-icon-document-copy",
    "component": "cmsReviewOrderList",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "order",
    "hidden": 1
  },
  {
    "title": "车队管理",
    "id": 86,
    "parent_id": 76,
    "route": "/cmsFleet",
    "icon": "el-icon-truck",
    "component": "cmsFleet",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "fleet",
    "hidden": 1
  },
  {
    "title": "新电厂订单",
    "id": 317,
    "parent_id": 76,
    "route": "/cmsPowerOrderNew",
    "icon": "el-icon-s-home",
    "component": "cmsPowerOrderNew",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "order",
    "hidden": 1
  },
  {
    "title": "电厂订单",
    "id": 180,
    "parent_id": 169,
    "route": "/cmsPowerOrderList",
    "icon": "el-icon-tickets",
    "component": "cmsPowerOrder",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "order",
    "hidden": 1
  },
  {
    "title": "货主流水",
    "id": 142,
    "parent_id": 140,
    "route": "/cmsFlow",
    "icon": "el-icon-s-finance",
    "component": "cmsFlowNew",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "flow",
    "hidden": 1
  },
  {
    "title": "财务管理",
    "id": 140,
    "parent_id": 0,
    "route": "/cmsFinance",
    "icon": "el-icon-s-data",
    "component": "layout",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "cms",
    "hidden": 1
  },
  {
    "title": "电厂管理",
    "id": 85,
    "parent_id": 76,
    "route": "/cmsPowerPlant",
    "icon": "el-icon-s-claim",
    "component": "cmsPowerPlant",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "powerPlat",
    "hidden": 1
  },
  {
    "title": "登陆日志",
    "id": 53,
    "parent_id": 38,
    "route": "/system/log/login",
    "icon": "el-icon-coin",
    "component": "loginLog",
    "redirect": "",
    "module": "system",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "loginLog",
    "hidden": 1
  },
  {
    "title": "已审核订单",
    "id": 315,
    "parent_id": 311,
    "route": "/auditedOrderList",
    "icon": "el-icon-s-order",
    "component": "cmsAuditedOrderList",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "order",
    "hidden": 1
  },
  {
    "title": "司机流水",
    "id": 167,
    "parent_id": 140,
    "route": "/cmsDriverFlow",
    "icon": "el-icon-document-copy",
    "component": "cmsDriverFlow",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "flow",
    "hidden": 1
  },
  {
    "title": "应收对账单",
    "id": 183,
    "parent_id": 140,
    "route": "/cmsReceiveState",
    "icon": "el-icon-s-data",
    "component": "cmsReceiveState",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "receiveState",
    "hidden": 1
  },
  {
    "title": "删除",
    "id": 139,
    "parent_id": 86,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "fleet@delete",
    "hidden": 1
  },
  {
    "title": "更新",
    "id": 138,
    "parent_id": 86,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "fleet@update",
    "hidden": 1
  },
  {
    "title": "应付对账单",
    "id": 184,
    "parent_id": 140,
    "route": "/cmsPayState",
    "icon": "el-icon-s-finance",
    "component": "cmsPayState",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "payState",
    "hidden": 1
  },
  {
    "title": "列表",
    "id": 137,
    "parent_id": 86,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "fleet@index",
    "hidden": 1
  },
  {
    "title": "创建",
    "id": 136,
    "parent_id": 86,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "fleet@save",
    "hidden": 1
  },
  {
    "title": "列表",
    "id": 367,
    "parent_id": 363,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "templateManager@index",
    "hidden": 1
  },
  {
    "title": "创建",
    "id": 366,
    "parent_id": 363,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "templateManager@save",
    "hidden": 1
  },
  {
    "title": "删除",
    "id": 365,
    "parent_id": 363,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "templateManager@delete",
    "hidden": 1
  },
  {
    "title": "更新",
    "id": 364,
    "parent_id": 363,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "templateManager@update",
    "hidden": 1
  },
  {
    "title": "模板管理",
    "id": 363,
    "parent_id": 75,
    "route": "/cmsTemplate",
    "icon": "el-icon-notebook-2",
    "component": "cmsTemplate",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "templateManager",
    "hidden": 1
  },
  {
    "title": "列表",
    "id": 356,
    "parent_id": 354,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "webSite@index",
    "hidden": 1
  },
  {
    "title": "更新",
    "id": 355,
    "parent_id": 354,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "webSite@webSiteSave",
    "hidden": 1
  },
  {
    "title": "官网配置",
    "id": 354,
    "parent_id": 38,
    "route": "/officia/index",
    "icon": "el-icon-s-tools",
    "component": "officiaIndex",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "webSite",
    "hidden": 1
  },
  {
    "title": "导出",
    "id": 346,
    "parent_id": 180,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "order@exportPowerOrderList",
    "hidden": 1
  },
  {
    "title": "导出",
    "id": 345,
    "parent_id": 317,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "order@exportPowerOrderNewList",
    "hidden": 1
  },
  {
    "title": "新增固废订单",
    "id": 344,
    "parent_id": 83,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "order@addGfOrder",
    "hidden": 1
  },
  {
    "title": "新增回收订单",
    "id": 343,
    "parent_id": 83,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "order@addHsOrder",
    "hidden": 1
  },
  {
    "title": "微信收款",
    "id": 342,
    "parent_id": 312,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "order@xtGfPayNew",
    "hidden": 1
  },
  {
    "title": "支付宝收款",
    "id": 341,
    "parent_id": 312,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "order@xtGfAliPayNew",
    "hidden": 1
  },
  {
    "title": "地磅审核",
    "id": 339,
    "parent_id": 314,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "order@weighbridgeReviewOrder",
    "hidden": 1
  },
  {
    "title": "导出",
    "id": 338,
    "parent_id": 315,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "order@exportAudited",
    "hidden": 1
  },
  {
    "title": "导出",
    "id": 337,
    "parent_id": 314,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "order@exportReview",
    "hidden": 1
  },
  {
    "title": "导出",
    "id": 336,
    "parent_id": 313,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "order@exportWaiting",
    "hidden": 1
  },
  {
    "title": "取消订单",
    "id": 335,
    "parent_id": 313,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "order@cancelOrderWaiting",
    "hidden": 1
  },
  {
    "title": "派单",
    "id": 334,
    "parent_id": 313,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "order@dispatchDriverSystem",
    "hidden": 1
  },
  {
    "title": "导出系统订单",
    "id": 332,
    "parent_id": 312,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "order@exportSystemOrder",
    "hidden": 1
  },
  {
    "title": "支付宝收款二维码",
    "id": 331,
    "parent_id": 317,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "order@powerOrderAliPayEwmNew",
    "hidden": 1
  },
  {
    "title": "微信收款二维码",
    "id": 330,
    "parent_id": 317,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "order@powerOrderPayEwmNew",
    "hidden": 1
  },
  {
    "title": "派单",
    "id": 329,
    "parent_id": 317,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "order@dispatchDriverPower",
    "hidden": 1
  },
  {
    "title": "取消订单",
    "id": 328,
    "parent_id": 317,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "order@cancelOrderPower",
    "hidden": 1
  },
  {
    "title": "派单",
    "id": 326,
    "parent_id": 317,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "order@dispatchDriver",
    "hidden": 1
  },
  {
    "title": "微信付款",
    "id": 325,
    "parent_id": 180,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "order@powerOrderPayEwm",
    "hidden": 1
  },
  {
    "title": "支付宝付款",
    "id": 324,
    "parent_id": 180,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "order@powerOrderAliPayEwm",
    "hidden": 1
  },
  {
    "title": "新增危废固废",
    "id": 323,
    "parent_id": 312,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "order@addXtHsOrder",
    "hidden": 1
  },
  {
    "title": "新增回收",
    "id": 322,
    "parent_id": 312,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "order@addXtGfOrder",
    "hidden": 1
  },
  {
    "title": "确认收款",
    "id": 321,
    "parent_id": 317,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "order@confirmPowerPay",
    "hidden": 1
  },
  {
    "title": "确认装货",
    "id": 320,
    "parent_id": 317,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "order@confirmPowerShip",
    "hidden": 1
  },
  {
    "title": "新增",
    "id": 319,
    "parent_id": 317,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "order@addPowerOrder",
    "hidden": 1
  },
  {
    "title": "站点流水",
    "id": 316,
    "parent_id": 140,
    "route": "/siteFlow",
    "icon": "el-icon-s-finance",
    "component": "siteFlow",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "siteFlow",
    "hidden": 1
  },
  {
    "title": "启用/禁用",
    "id": 309,
    "parent_id": 72,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "priceStandard@changeStatus",
    "hidden": 1
  },
  {
    "title": "编辑",
    "id": 308,
    "parent_id": 306,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "system",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "dictionary@update",
    "hidden": 1
  },
  {
    "title": "新增",
    "id": 307,
    "parent_id": 306,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "system",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "dictionary@save",
    "hidden": 1
  },
  {
    "title": "删除",
    "id": 305,
    "parent_id": 301,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "priceConfigData@delete",
    "hidden": 1
  },
  {
    "title": "编辑",
    "id": 304,
    "parent_id": 301,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "priceConfigData@update",
    "hidden": 1
  },
  {
    "title": "新增",
    "id": 303,
    "parent_id": 301,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "priceConfigData@save",
    "hidden": 1
  },
  {
    "title": "删除",
    "id": 299,
    "parent_id": 295,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "priceConfig@delete",
    "hidden": 1
  },
  {
    "title": "编辑",
    "id": 298,
    "parent_id": 295,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "priceConfig@update",
    "hidden": 1
  },
  {
    "title": "新增",
    "id": 297,
    "parent_id": 295,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "priceConfig@save",
    "hidden": 1
  },
  {
    "title": "处理",
    "id": 294,
    "parent_id": 292,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "feedfback@updateStatus",
    "hidden": 1
  },
  {
    "title": "地磅人员审核",
    "id": 293,
    "parent_id": 83,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "order@weighbridgeReview",
    "hidden": 1
  },
  {
    "title": "修改车队",
    "id": 291,
    "parent_id": 88,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "driver@updateFleet",
    "hidden": 1
  },
  {
    "title": "导入模板",
    "id": 290,
    "parent_id": 77,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "carType@template",
    "hidden": 1
  },
  {
    "title": "导入",
    "id": 289,
    "parent_id": 85,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "powerPlat@import",
    "hidden": 1
  },
  {
    "title": "导入模板",
    "id": 288,
    "parent_id": 85,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "powerPlat@template",
    "hidden": 1
  },
  {
    "title": "导入模板",
    "id": 287,
    "parent_id": 87,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "car@template",
    "hidden": 1
  },
  {
    "title": "导入",
    "id": 286,
    "parent_id": 87,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "car@import",
    "hidden": 1
  },
  {
    "title": "导入模板",
    "id": 285,
    "parent_id": 86,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "fleet@template",
    "hidden": 1
  },
  {
    "title": "导入",
    "id": 284,
    "parent_id": 86,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "fleet@import",
    "hidden": 1
  },
  {
    "title": "导入模板",
    "id": 283,
    "parent_id": 147,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "carFixLog@template",
    "hidden": 1
  },
  {
    "title": "导入",
    "id": 282,
    "parent_id": 147,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "carFixLog@import",
    "hidden": 1
  },
  {
    "title": "导入模板",
    "id": 281,
    "parent_id": 152,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "reimbursementType@template",
    "hidden": 1
  },
  {
    "title": "导入",
    "id": 280,
    "parent_id": 152,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "reimbursementType@import",
    "hidden": 1
  },
  {
    "title": "导入",
    "id": 279,
    "parent_id": 162,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "staffCommission@staffCommissionImport",
    "hidden": 1
  },
  {
    "title": "导入模板",
    "id": 278,
    "parent_id": 162,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "staffCommission@template",
    "hidden": 1
  },
  {
    "title": "导出",
    "id": 276,
    "parent_id": 83,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "order@exportOrder",
    "hidden": 1
  },
  {
    "title": "导出",
    "id": 275,
    "parent_id": 183,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "receiveState@exportReceiveState",
    "hidden": 1
  },
  {
    "title": "导出",
    "id": 274,
    "parent_id": 152,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "reimbursementType@exportReimbursementType",
    "hidden": 1
  },
  {
    "title": "导出",
    "id": 273,
    "parent_id": 77,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "carType@exportCarType",
    "hidden": 1
  },
  {
    "title": "导出",
    "id": 272,
    "parent_id": 85,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "powerPlat@exportPowerPlat",
    "hidden": 1
  },
  {
    "title": "导出",
    "id": 271,
    "parent_id": 82,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "hzAddress@exportUserAddress",
    "hidden": 1
  },
  {
    "title": "导出",
    "id": 270,
    "parent_id": 86,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "fleet@exportFleet",
    "hidden": 1
  },
  {
    "title": "导出",
    "id": 269,
    "parent_id": 87,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "car@exportCar",
    "hidden": 1
  },
  {
    "title": "导出",
    "id": 268,
    "parent_id": 147,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "carFixLog@exportCarFixLog",
    "hidden": 1
  },
  {
    "title": "导出",
    "id": 267,
    "parent_id": 182,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "HzContract@exportDriverUnbind",
    "hidden": 1
  },
  {
    "title": "导出",
    "id": 266,
    "parent_id": 88,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "driver@exportdriver",
    "hidden": 1
  },
  {
    "title": "导出",
    "id": 265,
    "parent_id": 74,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "site@exportSite",
    "hidden": 1
  },
  {
    "title": "导出",
    "id": 264,
    "parent_id": 184,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "payState@exportPayState",
    "hidden": 1
  },
  {
    "title": "导出",
    "id": 263,
    "parent_id": 167,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "flow@exportDriver",
    "hidden": 1
  },
  {
    "title": "导出",
    "id": 262,
    "parent_id": 142,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "flow@exportHZ",
    "hidden": 1
  },
  {
    "title": "导出",
    "id": 261,
    "parent_id": 143,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "reimbursement@export",
    "hidden": 1
  },
  {
    "title": "导出",
    "id": 260,
    "parent_id": 84,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "recharge@exportRecharge",
    "hidden": 1
  },
  {
    "title": "设置业务员",
    "id": 259,
    "parent_id": 81,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "users@setSalesman",
    "hidden": 1
  },
  {
    "title": "删除",
    "id": 258,
    "parent_id": 256,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "monitor",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "CrontabLog@delete",
    "hidden": 1
  },
  {
    "title": "列表",
    "id": 257,
    "parent_id": 256,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "monitor",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "CrontabLog@index",
    "hidden": 1
  },
  {
    "title": "任务日志",
    "id": 256,
    "parent_id": 249,
    "route": "/monitor/crontab/log/:crontab_id?",
    "icon": "el-icon-guide",
    "component": "crontabLog",
    "redirect": "",
    "module": "monitor",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "CrontabLog",
    "hidden": 2
  },
  {
    "title": "禁用/启用",
    "id": 255,
    "parent_id": 250,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "monitor",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "crontab@disOrEnable",
    "hidden": 1
  },
  {
    "title": "删除",
    "id": 254,
    "parent_id": 250,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "monitor",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "crontab@delete",
    "hidden": 1
  },
  {
    "title": "更新",
    "id": 253,
    "parent_id": 250,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "monitor",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "crontab@update",
    "hidden": 1
  },
  {
    "title": "保存",
    "id": 252,
    "parent_id": 250,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "monitor",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "crontab@save",
    "hidden": 1
  },
  {
    "title": "列表",
    "id": 251,
    "parent_id": 250,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "monitor",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "crontab@index",
    "hidden": 1
  },
  {
    "title": "定时任务",
    "id": 250,
    "parent_id": 249,
    "route": "/monitor/crontab",
    "icon": "el-icon-time",
    "component": "crontab",
    "redirect": "",
    "module": "monitor",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "crontab",
    "hidden": 1
  },
  {
    "title": "解绑车辆",
    "id": 243,
    "parent_id": 88,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "driver@driverUnCar",
    "hidden": 1
  },
  {
    "title": "设置车辆",
    "id": 242,
    "parent_id": 88,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "driver@driverUpdataCar",
    "hidden": 1
  },
  {
    "title": "佣金管理",
    "id": 240,
    "parent_id": 140,
    "route": "/cmsPromotion",
    "icon": "el-icon-s-ticket",
    "component": "cmsPromotion",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "promotion",
    "hidden": 1
  },
  {
    "title": "重置密码",
    "id": 239,
    "parent_id": 81,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "users@userUpdatePwd",
    "hidden": 1
  },
  {
    "title": "禁用/启用",
    "id": 238,
    "parent_id": 81,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "users@diablelUser",
    "hidden": 1
  },
  {
    "title": "禁用/启用",
    "id": 237,
    "parent_id": 88,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "driver@driverDisable",
    "hidden": 1
  },
  {
    "title": "信息查看",
    "id": 236,
    "parent_id": 181,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "powerPlat@getMyPowerInfo",
    "hidden": 1
  },
  {
    "title": "设置",
    "id": 235,
    "parent_id": 181,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "powerPlat@updateMyPower",
    "hidden": 1
  },
  {
    "title": "查看",
    "id": 234,
    "parent_id": 180,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "powerOrderList@read",
    "hidden": 1
  },
  {
    "title": "查看合同",
    "id": 232,
    "parent_id": 93,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "contract@read",
    "hidden": 1
  },
  {
    "title": "电厂设置",
    "id": 181,
    "parent_id": 169,
    "route": "/cmsPowerSetting",
    "icon": "el-icon-s-tools",
    "component": "cmsPowerSetting",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "powerPlat",
    "hidden": 1
  },
  {
    "title": "短信配置",
    "id": 179,
    "parent_id": 178,
    "route": "/sms/config",
    "icon": "el-icon-copy-document",
    "component": "sms",
    "redirect": "",
    "module": "sms",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "sms",
    "hidden": 1
  },
  {
    "title": "短信管理",
    "id": 178,
    "parent_id": 0,
    "route": "/sms",
    "icon": "el-icon-s-promotion",
    "component": "layout",
    "redirect": "",
    "module": "sms",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "sms",
    "hidden": 1
  },
  {
    "title": "电厂管理",
    "id": 169,
    "parent_id": 0,
    "route": "/cmsPlant",
    "icon": "el-icon-video-camera",
    "component": "layout",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "/cmsPlant",
    "hidden": 1
  },
  {
    "title": "区域管理",
    "id": 168,
    "parent_id": 73,
    "route": "/cmsArea",
    "icon": "el-icon-place",
    "component": "cmsArea",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "area",
    "hidden": 1
  },
  {
    "title": "合同管理",
    "id": 93,
    "parent_id": 75,
    "route": "/cmsContract",
    "icon": "el-icon-takeaway-box",
    "component": "cmsContract",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "contract",
    "hidden": 1
  },
  {
    "title": "充值管理",
    "id": 84,
    "parent_id": 76,
    "route": "/cmsRecharge",
    "icon": "el-icon-s-management",
    "component": "cmsRecharge",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "recharge",
    "hidden": 1
  },
  {
    "title": "订单管理",
    "id": 83,
    "parent_id": 76,
    "route": "/cmsOrderList",
    "icon": "el-icon-c-scale-to-original",
    "component": "cmsOrder",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "order",
    "hidden": 1
  },
  {
    "title": "地址管理",
    "id": 82,
    "parent_id": 76,
    "route": "/cmsAdress",
    "icon": "el-icon-office-building",
    "component": "cmsAdress",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "hzAddress",
    "hidden": 1
  },
  {
    "title": "公告管理",
    "id": 80,
    "parent_id": 75,
    "route": "/cmsNotice",
    "icon": "el-icon-chat-dot-square",
    "component": "cmsNotice",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "announce",
    "hidden": 1
  },
  {
    "title": "礼包管理",
    "id": 79,
    "parent_id": 75,
    "route": "/cmsGift",
    "icon": "el-icon-present",
    "component": "cmsGift",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "gift",
    "hidden": 1
  },
  {
    "title": "协议管理",
    "id": 78,
    "parent_id": 75,
    "route": "/cmsAgreement",
    "icon": "el-icon-money",
    "component": "cmsAgreement",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "agreement",
    "hidden": 1
  },
  {
    "title": "车型管理",
    "id": 77,
    "parent_id": 73,
    "route": "/cmsCarType",
    "icon": "el-icon-truck",
    "component": "cmsCarType",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "carType",
    "hidden": 1
  },
  {
    "title": "站点管理",
    "id": 74,
    "parent_id": 73,
    "route": "/cmsSite",
    "icon": "el-icon-wallet",
    "component": "cmsSite",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "site",
    "hidden": 1
  },
  {
    "title": "收费标准管理",
    "id": 72,
    "parent_id": 73,
    "route": "/cmsPriceStandard",
    "icon": "el-icon-s-operation",
    "component": "cmsPriceStandard",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "priceStandard",
    "hidden": 1
  },
  {
    "title": "禁用/启用",
    "id": 70,
    "parent_id": 68,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "system",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "module@disOrEnable",
    "hidden": 1
  },
  {
    "title": "列表",
    "id": 69,
    "parent_id": 68,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "system",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "module@index",
    "hidden": 1
  },
  {
    "title": "模块管理",
    "id": 68,
    "parent_id": 38,
    "route": "/system/module",
    "icon": "el-icon-postcard",
    "component": "module",
    "redirect": "",
    "module": "system",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "module",
    "hidden": 1
  },
  {
    "title": "开发者",
    "id": 67,
    "parent_id": 38,
    "route": "/system/develop",
    "icon": "el-icon-rank",
    "component": "develop",
    "redirect": "",
    "module": "system",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "develop",
    "hidden": 1
  },
  {
    "title": "删除",
    "id": 66,
    "parent_id": 62,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "system",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "sensitiveWord@delete",
    "hidden": 1
  },
  {
    "title": "更新",
    "id": 65,
    "parent_id": 62,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "system",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "sensitiveWord@update",
    "hidden": 1
  },
  {
    "title": "新增",
    "id": 64,
    "parent_id": 62,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "system",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "sensitiveWord@save",
    "hidden": 1
  },
  {
    "title": "列表",
    "id": 63,
    "parent_id": 62,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "system",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "sensitiveWord@index",
    "hidden": 1
  },
  {
    "title": "敏感词库",
    "id": 62,
    "parent_id": 38,
    "route": "/sensitive/word",
    "icon": "el-icon-folder-delete",
    "component": "sensitiveWord",
    "redirect": "",
    "module": "system",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "sensitiveWord",
    "hidden": 1
  },
  {
    "title": "预览",
    "id": 61,
    "parent_id": 59,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "system",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "generate@preview",
    "hidden": 1
  },
  {
    "title": "生成",
    "id": 60,
    "parent_id": 59,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "system",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "generate@save",
    "hidden": 1
  },
  {
    "title": "代码生成",
    "id": 59,
    "parent_id": 38,
    "route": "/system/generate",
    "icon": "el-icon-scissors",
    "component": "generate",
    "redirect": "",
    "module": "system",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "generate",
    "hidden": 1
  },
  {
    "title": "清空",
    "id": 58,
    "parent_id": 56,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "system",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "operatelog@empty",
    "hidden": 1
  },
  {
    "title": "列表",
    "id": 57,
    "parent_id": 56,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "system",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "operatelog@list",
    "hidden": 1
  },
  {
    "title": "操作日志",
    "id": 56,
    "parent_id": 38,
    "route": "/system/log/operate",
    "icon": "el-icon-house",
    "component": "operateLog",
    "redirect": "",
    "module": "system",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "operateLog",
    "hidden": 1
  },
  {
    "title": "清空",
    "id": 55,
    "parent_id": 53,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "system",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "loginlog@empty",
    "hidden": 1
  },
  {
    "title": "列表",
    "id": 54,
    "parent_id": 53,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "system",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "loginlog@list",
    "hidden": 1
  },
  {
    "title": "获取",
    "id": 52,
    "parent_id": 49,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "system",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "config@read",
    "hidden": 1
  },
  {
    "title": "存储",
    "id": 51,
    "parent_id": 49,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "system",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "config@save",
    "hidden": 1
  },
  {
    "title": "父级配置",
    "id": 50,
    "parent_id": 49,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "system",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "config@parent",
    "hidden": 1
  },
  {
    "title": "上传文件",
    "id": 48,
    "parent_id": 44,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "system",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "upload@file",
    "hidden": 1
  },
  {
    "title": "上传图片",
    "id": 47,
    "parent_id": 44,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "system",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "upload@image",
    "hidden": 1
  },
  {
    "title": "删除",
    "id": 46,
    "parent_id": 44,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "system",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "attachments@delete",
    "hidden": 1
  },
  {
    "title": "列表",
    "id": 45,
    "parent_id": 44,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "system",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "attachments@index",
    "hidden": 1
  },
  {
    "title": "备份",
    "id": 43,
    "parent_id": 39,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "system",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "optimize@backup",
    "hidden": 1
  },
  {
    "title": "优化",
    "id": 42,
    "parent_id": 39,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "system",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "dataDictionary@optimize",
    "hidden": 1
  },
  {
    "title": "查看",
    "id": 40,
    "parent_id": 39,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "system",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "dataDictionary@view",
    "hidden": 1
  },
  {
    "title": "系统管理",
    "id": 38,
    "parent_id": 0,
    "route": "/system",
    "icon": "el-icon-s-tools",
    "component": "layout",
    "redirect": "attactments",
    "module": "system",
    "keepAlive": 2,
    "type": 1,
    "permission_mark": "system",
    "hidden": 1
  },
  {
    "title": "获取全部",
    "id": 37,
    "parent_id": 32,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "permissions",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "job@getAll",
    "hidden": 2
  },
  {
    "title": "删除",
    "id": 36,
    "parent_id": 32,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "permissions",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "job@delete",
    "hidden": 2
  },
  {
    "title": "更新",
    "id": 35,
    "parent_id": 32,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "permissions",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "job@update",
    "hidden": 2
  },
  {
    "title": "保存",
    "id": 34,
    "parent_id": 32,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "permissions",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "job@save",
    "hidden": 2
  },
  {
    "title": "列表",
    "id": 33,
    "parent_id": 32,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "permissions",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "job@indexs",
    "hidden": 2
  },
  {
    "title": "岗位管理",
    "id": 32,
    "parent_id": 1,
    "route": "/permissions/jobs",
    "icon": "el-icon-setting",
    "component": "jobs",
    "redirect": "",
    "module": "permissions",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "job",
    "hidden": 1
  },
  {
    "title": "删除",
    "id": 31,
    "parent_id": 27,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "permissions",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "department@delete",
    "hidden": 1
  },
  {
    "title": "更新",
    "id": 30,
    "parent_id": 27,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "permissions",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "department@update",
    "hidden": 1
  },
  {
    "title": "保存",
    "id": 29,
    "parent_id": 27,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "permissions",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "department@save",
    "hidden": 1
  },
  {
    "title": "列表",
    "id": 28,
    "parent_id": 27,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "permissions",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "department@index",
    "hidden": 1
  },
  {
    "title": "权限方法",
    "id": 26,
    "parent_id": 19,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "permissions",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "permission@getMethods",
    "hidden": 1
  },
  {
    "title": "删除",
    "id": 25,
    "parent_id": 19,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "permissions",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "permission@delete",
    "hidden": 1
  },
  {
    "title": "更新",
    "id": 24,
    "parent_id": 19,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "permissions",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "permission@update",
    "hidden": 1
  },
  {
    "title": "禁用/启用",
    "id": 23,
    "parent_id": 19,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "permissions",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "permission@show",
    "hidden": 1
  },
  {
    "title": "保存",
    "id": 22,
    "parent_id": 19,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "permissions",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "permission@save",
    "hidden": 1
  },
  {
    "title": "创建",
    "id": 21,
    "parent_id": 19,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "permissions",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "permission@create",
    "hidden": 1
  },
  {
    "title": "列表",
    "id": 20,
    "parent_id": 19,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "permissions",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "permission@index",
    "hidden": 1
  },
  {
    "title": "权限获取",
    "id": 18,
    "parent_id": 11,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "permissions",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "role@getPermissions",
    "hidden": 1
  },
  {
    "title": "删除",
    "id": 17,
    "parent_id": 11,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "permissions",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "role@delete",
    "hidden": 1
  },
  {
    "title": "更新",
    "id": 16,
    "parent_id": 11,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "permissions",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "role@update",
    "hidden": 1
  },
  {
    "title": "查看",
    "id": 15,
    "parent_id": 11,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "permissions",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "role@edit",
    "hidden": 1
  },
  {
    "title": "保存",
    "id": 14,
    "parent_id": 11,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "permissions",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "role@save",
    "hidden": 1
  },
  {
    "title": "创建",
    "id": 13,
    "parent_id": 11,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "permissions",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "role@create",
    "hidden": 1
  },
  {
    "title": "列表",
    "id": 12,
    "parent_id": 11,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "permissions",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "role@index",
    "hidden": 1
  },
  {
    "title": "恢复",
    "id": 10,
    "parent_id": 2,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "permissions",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "user@recover",
    "hidden": 1
  },
  {
    "title": "禁用",
    "id": 9,
    "parent_id": 2,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "permissions",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "user@switchStatus",
    "hidden": 1
  },
  {
    "title": "删除",
    "id": 8,
    "parent_id": 2,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "permissions",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "user@delete",
    "hidden": 1
  },
  {
    "title": "更新",
    "id": 7,
    "parent_id": 2,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "permissions",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "user@update",
    "hidden": 1
  },
  {
    "title": "查看",
    "id": 6,
    "parent_id": 2,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "permissions",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "user@edit",
    "hidden": 1
  },
  {
    "title": "保存",
    "id": 5,
    "parent_id": 2,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "permissions",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "user@save",
    "hidden": 1
  },
  {
    "title": "创建",
    "id": 4,
    "parent_id": 2,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "permissions",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "user@create",
    "hidden": 1
  },
  {
    "title": "列表",
    "id": 3,
    "parent_id": 2,
    "route": "",
    "icon": "",
    "component": "",
    "redirect": "",
    "module": "permissions",
    "keepAlive": 1,
    "type": 2,
    "permission_mark": "user@index",
    "hidden": 1
  },
  {
    "title": "报销类型管理",
    "id": 152,
    "parent_id": 76,
    "route": "/cmsReimbursementType",
    "icon": "el-icon-s-flag",
    "component": "cmsReimbursementType",
    "redirect": "",
    "module": "cms",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "reimbursementType",
    "hidden": 1
  },
  {
    "title": "系统监控",
    "id": 249,
    "parent_id": 0,
    "route": "/monitor",
    "icon": "el-icon-view",
    "component": "layout",
    "redirect": "/monitor/crontab",
    "module": "monitor",
    "keepAlive": 1,
    "type": 1,
    "permission_mark": "monitor",
    "hidden": 1
  }
]